'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
function hashFile(file){const h=crypto.createHash('sha256'),fd=fs.openSync(file,'r'),b=Buffer.alloc(65536);try{let n;while((n=fs.readSync(fd,b,0,b.length,null))>0)h.update(b.subarray(0,n));return h.digest('hex').toUpperCase();}finally{fs.closeSync(fd);}}
function locked(dir,action){fs.mkdirSync(dir,{recursive:true});const name=path.join(dir,'.publish.lock');let fd;try{fd=fs.openSync(name,'wx');}catch{throw Error('Veröffentlichung gesperrt. Laufenden Vorgang prüfen; verwaiste .publish.lock erst nach Prüfung entfernen.');}try{return action();}finally{fs.closeSync(fd);fs.unlinkSync(name);}}
function manifest(dir,m){const temp=path.join(dir,`.manifest-${crypto.randomUUID()}.tmp`);try{const fd=fs.openSync(temp,'wx');try{fs.writeFileSync(fd,JSON.stringify(m,null,2)+'\n');fs.fsyncSync(fd);}finally{fs.closeSync(fd);}fs.renameSync(temp,path.join(dir,'manifest.json'));}finally{if(fs.existsSync(temp))fs.unlinkSync(temp);}}
// Internal step: Windows entrypoint must verify Authenticode on the staged bytes first.
function publishVerified(dir,o){if(!/^\d+\.\d+\.\d+\.\d+$/.test(o.version||'')||!String(o.revision||'').trim())throw Error('Version/Revision ungültig.');if(!/^[A-F0-9]{64}$/.test(o.sha256||'')||!/^[A-F0-9]{40}$/.test(o.signer_thumbprint||''))throw Error('Geprüfte SHA256 und Signer erforderlich.');return locked(dir,()=>{const filename=`TOR-POS-Pro-Setup-${o.sha256}.exe`,target=path.join(dir,filename),tmp=path.join(dir,`.setup-${crypto.randomUUID()}.tmp`);try{fs.copyFileSync(o.source,tmp,fs.constants.COPYFILE_EXCL);if(hashFile(tmp)!==o.sha256)throw Error('Setup nach Prüfung verändert.');const fd=fs.openSync(tmp,'r+');try{fs.fsyncSync(fd);}finally{fs.closeSync(fd);}if(fs.existsSync(target)){if(hashFile(target)!==o.sha256)throw Error('Vorhandenes Setup beschädigt.');}else fs.renameSync(tmp,target);const m={enabled:true,version:o.version,revision:o.revision,published_at:new Date().toISOString(),mandatory:!!o.mandatory,editions:['KIOSK','IMBISS'],filename,sha256:o.sha256,signer_thumbprint:o.signer_thumbprint,release_notes:String(o.release_notes||'')};manifest(dir,m);return m;}finally{if(fs.existsSync(tmp))fs.unlinkSync(tmp);}});}
function disable(dir){return locked(dir,()=>{const m=JSON.parse(fs.readFileSync(path.join(dir,'manifest.json'),'utf8'));m.enabled=false;manifest(dir,m);});}
module.exports={publishVerified,disable,hashFile};
if(require.main===module)try{const [action,dir,input]=process.argv.slice(2);if(action==='publish')publishVerified(dir,JSON.parse(fs.readFileSync(input,'utf8').replace(/^\uFEFF/,'')));else if(action==='disable')disable(dir);else throw Error('Ungültige Aktion.');}catch(e){console.error(e.message);process.exitCode=1;}
