<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TorDemoBuild)' == 'true'">
    <DefineConstants>$(DefineConstants);TOR_DEMO_BUILD</DefineConstants>
  </PropertyGroup>
</Project>
