#define MyAppName "TOR KIOSK"
#define MyAppId "{{A4E3F6A1-4B7A-4F51-8D7E-2C4A8B9F1D21}"
#define MyDefaultDirName "TOR KIOSK"
#define MyDefaultGroupName "TOR KIOSK"
#define MyAppExeName "TOR-KIOSK.exe"
#define MyAppMutex "TOR-KIOSK-Running"
#define MyDataDirName "TOR-KIOSK"
#define MyProcessName "TOR-KIOSK"
#define MyProductEdition "KIOSK"
#define MyOutputBaseFilename "TOR-KIOSK-Setup"
#define MyPublishDir "publish\split\TOR-KIOSK"
#include "TOR-POS-Pro-Setup.iss"
