#define MyAppName "TOR Gastro"
#define MyAppId "{{B7D2C9E4-6A35-4C88-9F12-5E71A3D8C642}"
#define MyDefaultDirName "TOR Gastro"
#define MyDefaultGroupName "TOR Gastro"
#define MyAppExeName "TOR-Gastro.exe"
#define MyAppMutex "TOR-Gastro-Running"
#define MyDataDirName "TOR-Gastro"
#define MyProcessName "TOR-Gastro"
#define MyProductEdition "IMBISS"
#define MyOutputBaseFilename "TOR-Gastro-Setup"
#define MyPublishDir "publish\split\TOR-Gastro"
#include "TOR-POS-Pro-Setup.iss"
