#define MyAppName "TOR DÖNER"
#define MyAppId "{{B7D2C9E4-6A35-4C88-9F12-5E71A3D8C642}"
#define MyDefaultDirName "TOR DÖNER"
#define MyDefaultGroupName "TOR DÖNER"
#define MyAppExeName "TOR-DOENER.exe"
#define MyAppMutex "TOR-DOENER-Running"
#define MyDataDirName "TOR-DOENER"
#define MyProcessName "TOR-DOENER"
#define MyProductEdition "IMBISS"
#define MyOutputBaseFilename "TOR-DOENER-Setup"
#define MyPublishDir "publish\split\TOR-DOENER"
#include "TOR-POS-Pro-Setup.iss"
