#define MyAppName "TOR Restaurant"
#define MyAppId "{{D3C7A812-9B5E-4F61-A2D4-7C8E9F103B52}"
#define MyDefaultDirName "TOR Restaurant"
#define MyDefaultGroupName "TOR Restaurant"
#define MyAppExeName "TOR-Restaurant.exe"
#define MyAppMutex "TOR-Restaurant-Running"
#define MyDataDirName "TOR-Restaurant"
#define MyProcessName "TOR-Restaurant"
#define MyProductEdition "RESTAURANT"
#define MyOutputBaseFilename "TOR-Restaurant-Setup"
#define MyPublishDir "publish\split\TOR-Restaurant"
#include "TOR-POS-Pro-Setup.iss"
