#define MyAppName "TOR Einzelhandel"
#define MyAppId "{{A4E3F6A1-4B7A-4F51-8D7E-2C4A8B9F1D21}"
#define MyDefaultDirName "TOR Einzelhandel"
#define MyDefaultGroupName "TOR Einzelhandel"
#define MyAppExeName "TOR-Einzelhandel.exe"
#define MyAppMutex "TOR-Einzelhandel-Running"
#define MyDataDirName "TOR-Einzelhandel"
#define MyProcessName "TOR-Einzelhandel"
#define MyProductEdition "KIOSK"
#define MyOutputBaseFilename "TOR-Einzelhandel-Setup"
#define MyPublishDir "publish\split\TOR-Einzelhandel"
#include "TOR-POS-Pro-Setup.iss"
